"""add agent type and temperature for Agents

Revision ID: 575acdd96cb4
Revises: 653159ebd7f5
Create Date: 2025-05-30 22:56:09.496548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '575acdd96cb4'
down_revision: Union[str, None] = '653159ebd7f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('agent_type', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('temperature', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'temperature')
    op.drop_column('agents', 'agent_type')
    # ### end Alembic commands ###
