"""add coin count for User

Revision ID: 9846e7e94677
Revises: 07cc2dbdfc3a
Create Date: 2025-05-26 00:02:40.598275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9846e7e94677'
down_revision: Union[str, None] = '07cc2dbdfc3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'users',
        sa.Column('coin_count', sa.Integer(), nullable=False, server_default='1000')
    )
    op.alter_column('users', 'coin_count', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'coin_count')
    # ### end Alembic commands ###
