"""change to nullable = False and set default values

Revision ID: b6cd52f5bf0a
Revises: 575acdd96cb4
Create Date: 2025-05-30 22:58:01.704761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6cd52f5bf0a'
down_revision: Union[str, None] = '575acdd96cb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'agent_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('agents', 'temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('agents', 'agent_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
