"""Add agent_id to chat_history

Revision ID: dd0c3f0f1501
Revises: 9846e7e94677
Create Date: 2025-05-26 00:59:49.823546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd0c3f0f1501'
down_revision: Union[str, None] = '9846e7e94677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('agent_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'chat_history', 'agents', ['agent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.drop_column('chat_history', 'agent_id')
    # ### end Alembic commands ###
